# https://www.home-assistant.io/integrations/default_config/
default_config:

logger:
  default: critical
  logs:
    custom_components.fglair_heatpump_controller.climate: debug
    homeassistant: debug
