name: Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Tag of the release where to upload the zip (e.g. v0.0.1)'
        required: true
        type: string

jobs:
  release:
    name: "Create Release Package"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v4

      - name: "Create zip package"
        run: |
          cd custom_components/fglair_heatpump_controller
          zip fglair_heatpump_controller.zip -r ./

      - name: "Upload zip to release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ inputs.version || github.event.release.tag_name }}
        run: |
          gh release upload ${TAG_NAME} custom_components/fglair_heatpump_controller/fglair_heatpump_controller.zip
